### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a data model to indicate which direction the car is facing.
- [x] Query the F1 Car.
- [x] Add an event listener for 'keydown'.
- [x] According to the keydown arrows, rotate F1 Car.
- [x] Remove unnecessary codes.
