### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add properties for x and y coordinates on data model.
- [x] Use absolute positioning on the F1 Car image.
- [x] Create a movement variable set to 0.
- [x] Create a setInterval with arguments startCar and 16.
- [x] Inside startCar function, increment movement, and set the left offset property to movement and concatenate 'rem'.
- [x] Inside the data model, xCoordinate will equal to movement.
- [x] remove unnecessary codes.
