### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by DevJosephLee** [DevJosephLee/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started.
- [x] Add event listener for keydown, name function startStopCar.
- [x] Inside the StartStopCar function, if the space key is pressed, and car is not started
- [x] call setInterval on carMovement function with 16 milliseconds delay.
- [x] else if space key is pressed and car is started in data model
- [x] clear interval on interval
- [x] and car is stopped in data model.
- [x] remove any unnecessary codes
